# Generated by Django 4.1.7 on 2023-03-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_category_category_status_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
