# Generated by Django 4.1.7 on 2023-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_task_category_remove_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('NEW', 'unassigned'), ('URGENT_AND_IMPORTANT', 'urgent and important'), ('URGENT_AND_NOT_IMPORTANT', 'urgent and not important'), ('URGENT_BUT_NOT_IMPORTANT', 'urgent but not important'), ('NOT_URGENT_AND_NOT_IMPORTANT', 'not urgent and not important')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED_YET', 'not started yet'), ('IN_PROGRESS', 'in progress'), ('PENDING', 'pending'), ('DONE', 'done')], max_length=50, null=True),
        ),
    ]
