# Generated by Django 4.1.7 on 2023-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_task_category_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('new', 'unassigned'), ('urgent and important', 'urgent and important'), ('not urgent and important', 'urgent and not important'), ('urgent but not important', 'urgent but not important'), ('not urgent and not important', 'not urgent and not important')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started yet', 'not started yet'), ('in progres...', 'in progress'), ('pending', 'pending'), ('done', 'done')], max_length=50, null=True),
        ),
    ]
