# Generated by Django 4.1.7 on 2023-03-15 20:49

from django.db import migrations, models
import todolist.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_task_category_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=todolist.models.due_date),
        ),
    ]
